// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcwSmZHdEaI7z7IKlTNHgCxhF4E30KU2g',
    appId: '1:417688163567:web:8bcf8d381371e08adbf71a',
    messagingSenderId: '417688163567',
    projectId: 'portfolio-14851',
    authDomain: 'portfolio-14851.firebaseapp.com',
    storageBucket: 'portfolio-14851.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi8CSVQ3VG4xfVXK834rs6VeScfyD7Cg8',
    appId: '1:417688163567:android:c1e55df79dfd247edbf71a',
    messagingSenderId: '417688163567',
    projectId: 'portfolio-14851',
    storageBucket: 'portfolio-14851.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mnhbHi7tbxXdNl5u4QVDEa4JMElnQ60',
    appId: '1:417688163567:ios:fe813285bece6c0bdbf71a',
    messagingSenderId: '417688163567',
    projectId: 'portfolio-14851',
    storageBucket: 'portfolio-14851.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9mnhbHi7tbxXdNl5u4QVDEa4JMElnQ60',
    appId: '1:417688163567:ios:c652cacdbc1938f7dbf71a',
    messagingSenderId: '417688163567',
    projectId: 'portfolio-14851',
    storageBucket: 'portfolio-14851.appspot.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
